[WIP] Render url without styling
nilenso/reader pull request #5
Opened 2020-10-28 10:32 UTC by qptr

2020-10-29 12:11 UTC, qptr commented
could use some formatting. maybe another pr

![reader-browser](https://user-images.githubusercontent.com/71076330/97570346-813ba980-1a0d-11eb-9f5a-30ab6002c096.png)

2020-10-30 05:11 UTC, jysandy requested changes

2020-10-30 05:11 UTC, jysandy commented on src/reader/html.clj
> +    (assoc node :content
Use `update` here instead of `assoc`.

2020-10-30 05:11 UTC, jysandy commented on src/reader/html.clj
> +               (= (:tag node) :link)))
Check the `rel` attribute on links, to make sure that they are in fact linking to a stylesheet.

2020-11-02 06:32 UTC, jysandy approved these changes

2020-11-02 06:32 UTC, merged